theme: minima
breadcrumbs: true
show_downloads: true
include: ["_pages"]

search: true

defaults:
  #posts
  - scope:
      path: ""
      type: posts
      toc: true
      toc_label: "Introduction Topics"
    values:
      read_time: true
